/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alumni.project;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class SchoolD extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection con;
    Statement stmt;
    int f;

    /**
     * Creates new form SchoolD
     */
    public SchoolD() {
        initComponents();
         
        pUpdate.setVisible(false);
        disable1();
        model=(DefaultTableModel)tbSchoolD.getModel();
        Date dt= new Date();
        txtDOB.setDate(dt);
        show1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
             
             void setdata( String x)
    {
        try
        {
            int x1=Integer.parseInt(x);
                    OpenConnection();
                    String q="select * from SchoolD where StudentId ='" + x + "';";
                    ResultSet rs =stmt.executeQuery(q);
                    rs.next();
                    String SId= rs.getString("StudentId");
                    txtSId.setText(SId);
                    String nm= rs.getString("name");
                    txtName.setText(nm);
                     String Gnm= rs.getString("GuardianName");
                    txtGname.setText(Gnm);
                     String eca= rs.getString("ECA");
                    txtECA.setText(eca);
                    String HAdd= rs.getString("HomeAdd");
                    txtHAdd.setText(HAdd);
                    
                    String div=rs.getString("division");
                    cmbD.setSelectedItem(div);
                    String cst=rs.getString("cast");
                    if (cst.compareTo("Scheduled Cast")==0)
                    {
                        rdSC.setSelected(true);
                    }
                    else if (cst.compareTo("Scheduled Tribe")==0)
                    {
                        rdST.setSelected(true);
                    }
                    else if (cst.compareTo("OBC")==0)
                    {
                        rdOBC.setSelected(true);
                    }
                    else
                    {
                        rdGen.setSelected(true);
                    }
                    Date d1=rs.getDate("DOB");
                    txtDOB.setDate(d1);
                    
        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e.getMessage());
                }
    }
             
     void OpenConnection()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/alumni","root","root");
            stmt=con.createStatement();
            
        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e.getMessage());
                }
    }
     
     
     
     
     
     void show1()
  {
      delete1();
      try{
          OpenConnection();
          String query="select * from SchoolD";
          ResultSet rs=stmt.executeQuery(query);
          while(rs.next())
          {
              String SId =rs.getString("StudentId");
              String Name=rs.getString("Name");
              String ECA=rs.getString("ECA");
              String Div=rs.getString("Division");
              String gName=rs.getString("GuardianName");
              String Cast=rs.getString("Cast");
              String HomeAdd=rs.getString("HomeAdd");
              String DOB=rs.getString("DOB");
              model.addRow(new Object[]{SId,Name,gName,Cast,DOB,HomeAdd,ECA, Div});
          }
          rs.close();
          stmt.close();
          con.close();
          
      }
      catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
      }
      
  }
     void delete1()
  {
      int rows=model.getRowCount();
      if (rows>0)
      {
          for( int i=0; i<rows;i++)
          {
              model.removeRow(0);
          }
              
          
      }
  }
  
     
     
      void enable1()
 {
     txtName.setEditable(true);
     txtGname.setEditable(true);
     txtECA.setEditable(true);
     txtSId.setEditable(true);
     txtHAdd.setEditable(true);
     cmbD.setEnabled(true);
     rdSC.setEnabled(true);
     rdST.setEnabled(true);
     rdGen.setEnabled(true); 
     rdOBC.setEnabled(true);
 }
 
  void disable1()
 {
     txtName.setEditable(false);
     txtGname.setEditable(false);
     txtECA.setEditable(false);
     txtSId.setEditable(false);
     txtHAdd.setEditable(false);
     cmbD.setEnabled(false);
     rdSC.setEnabled(false);
     rdST.setEnabled(false);
     rdGen.setEnabled(false); 
     rdOBC.setEnabled(false);
 }
  void clear()
  {
      txtName.setText("");
      txtGname.setText("");
     txtECA.setText("");
     txtSId.setText("");
     txtHAdd.setText("");
     cmbD.setSelectedItem(0);
     
     rdSC.setEnabled(false);
     rdST.setEnabled(false);
      rdOBC.setEnabled(false);
     rdGen.setEnabled(false);
     
  }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pAdd = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtSId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cmbD = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGname = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdSC = new javax.swing.JRadioButton();
        rdST = new javax.swing.JRadioButton();
        rdOBC = new javax.swing.JRadioButton();
        rdGen = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSchoolD = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtECA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHAdd = new javax.swing.JTextField();
        pUpdate = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAddLayout = new javax.swing.GroupLayout(pAdd);
        pAdd.setLayout(pAddLayout);
        pAddLayout.setHorizontalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pAddLayout.setVerticalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2)
                    .addComponent(btnDelete)
                    .addComponent(jButton4)
                    .addComponent(btnSearch)
                    .addComponent(jButton1)))
        );

        jLabel1.setText("Enter Student Id:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Name:");

        jLabel3.setText("Date of Birth:");

        cmbD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4" }));

        jLabel4.setText("Division:");

        jLabel5.setText("Guardian Name:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cast"));

        buttonGroup1.add(rdSC);
        rdSC.setText("Scheduled Cast");

        buttonGroup1.add(rdST);
        rdST.setText("Scheduled Tribe");

        buttonGroup1.add(rdOBC);
        rdOBC.setText("OBC");

        buttonGroup1.add(rdGen);
        rdGen.setText("General");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdST)
                    .addComponent(rdOBC)
                    .addComponent(rdGen)
                    .addComponent(rdSC))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdSC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdST)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdOBC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdGen)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tbSchoolD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Guardian Name", "Cast", "DOB", "Home Address", "Extra Curricular Activity", "Division"
            }
        ));
        jScrollPane2.setViewportView(tbSchoolD);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel6.setText("Extra Curricular Activities:");

        jLabel7.setText("Home Address:");

        pUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton6.setText("CANCEL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUpdateLayout = new javax.swing.GroupLayout(pUpdate);
        pUpdate.setLayout(pUpdateLayout);
        pUpdateLayout.setHorizontalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnUpdate)
                .addGap(51, 51, 51)
                .addComponent(jButton6)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pUpdateLayout.setVerticalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(jButton6))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel5))
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txtSId)
                    .addComponent(cmbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGname, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txtECA)
                    .addComponent(txtHAdd))
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtECA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     pAdd.setVisible(false); 
   pUpdate.setVisible(true);
   enable1();
   f=0;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
          try
      {
          String SId=txtSId.getText();
          String nm=txtName.getText();
          String Gnm = txtGname.getText();
          String ECA = txtECA.getText();
          String HAdd = txtHAdd.getText();
          
          String div=(String)cmbD.getSelectedItem();
          SimpleDateFormat s= new SimpleDateFormat("yyyy-MM-dd");
          Date d= txtDOB.getDate();
          String dob=s.format(d);
          String cast="";
          
          if (rdSC.isSelected()==true)
          {
              cast="Scheduled Cast";
          }
          else if (rdST.isSelected()==true)
          {
              cast="Scheduled Tribe";
          }
            else if (rdOBC.isSelected()==true)
          {
              cast="Other Backward Class";
          }
            else if (rdGen.isSelected()==true)
          {
              cast="General";
          }
          OpenConnection();
          if((SId.compareTo("")!=0)&&(nm.compareTo("")!=0)&&(Gnm.compareTo("")!=0)&&(HAdd.compareTo("")!=0)&&(div.compareTo("")!=0)&&(ECA.compareTo("Select Any One")!=0)&&(dob.compareTo("")!=0)&&(cast.compareTo("")!=0))
          {
              if (f==0)
              {
                  String q ="";
                  q = "Insert into SchoolD values(" + SId + "," + "'" + div + "'" + "," + "'" + dob + "'" + "," + "'" + ECA + "'" + "," +"'"+HAdd+ "'" + "," +"'"+ cast + "'" + "," +"'"+ Gnm + "'" + "," + "'"+ nm + "'" + ");" ;
              stmt.executeUpdate(q);
              con.close();
              }
              if (f==1)
              {
                  String q="update SchoolD set  Division ='"+div+"',DOB='"+dob+"',ECA='"+ECA+  "', HomeAdd ='"+HAdd+   "', Cast ='" +cast+    "', GuardianName ='" + Gnm + "', Name ='"+ nm +"' where Studentid = '" + SId + "';";
                  stmt.executeUpdate(q);
                  con.close();
              }
              JOptionPane.showMessageDialog(null, "record updated");
              clear();
              disable1();
              pUpdate.setVisible(false);
              pAdd.setVisible(true);
              show1();
              f=2;
              
              
          }
          else
          {
              JOptionPane.showMessageDialog(null, "fields seem to be blank");
          }
          
          
      }
      catch(Exception e)
              {
                 JOptionPane.showMessageDialog(null, e.getMessage());
              }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
           String x= JOptionPane.showInputDialog("Enter the StudentId");
           
           if( x.compareTo("")!=0)
           {
                setdata(x); 
                enable1();
                txtSId.setEnabled(false);
                pAdd.setVisible(false);
                pUpdate.setVisible(true);
                f=1;
           }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

          
        try{
           String x= JOptionPane.showInputDialog("Enter the StudentId");
           
           if( x.compareTo("")!=0)
           {
                setdata(x); 
                enable1();
                String SId=txtSId.getText();
                txtSId.setEnabled(false);
                pAdd.setVisible(false);
                pUpdate.setVisible(true);
          
                OpenConnection();
                
         int a= JOptionPane.showConfirmDialog(null,"Are you sure you want to delete");
          
         if(a==0)
         {
            String q1="delete from SchoolD where studentId='"+SId+"';"; 
            stmt.execute(q1);
            String q2="delete from AlumniD where studentId='"+SId+"';"; 
            stmt.execute(q2);
            
            JOptionPane.showMessageDialog(null,"record deleted");
            
            con.close();
             show1();
         }
         else
         {
             JOptionPane.showMessageDialog(null,"record not deleted");
             con.close();
         }
         
        
           }
       }
       catch(Exception e)
       {
           //JOptionPane.showMessageDialog(null,e.getMessage());
       }// TODO add your handling code here:
                                             

        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
  SearchA s1= new SearchA();
        s1.show();
        hide();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   clear();
     disable1();
     pUpdate.setVisible(false);
     pAdd.setVisible(true);
     JOptionPane.showMessageDialog(null, "NO changes have been made in the table");      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Menu m1=new Menu();
          m1.show();
           hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pAdd;
    private javax.swing.JPanel pUpdate;
    private javax.swing.JRadioButton rdGen;
    private javax.swing.JRadioButton rdOBC;
    private javax.swing.JRadioButton rdSC;
    private javax.swing.JRadioButton rdST;
    private javax.swing.JTable tbSchoolD;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtECA;
    private javax.swing.JTextField txtGname;
    private javax.swing.JTextField txtHAdd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSId;
    // End of variables declaration//GEN-END:variables
}
