/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alumni.project;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Student
 */
public class SearchA extends javax.swing.JFrame {

    /**
     * Creates new form SearchA
     */
    
     Connection con;
     Connection con1;
Statement stmt;
Statement stmt1;


DefaultTableModel model;
DefaultTableModel model1;
DefaultTableModel model2;
    
    public SearchA() {
        initComponents();
        OpenConnection();
        model=(DefaultTableModel)tab.getModel();
         model1=(DefaultTableModel)tab1.getModel();
          model2=(DefaultTableModel)tab2.getModel();
    }
    
void OpenConnection()
{ 
    try{
        Class.forName("com.mysql.jdbc.Driver");
        con= DriverManager.getConnection("jdbc:mysql://localhost:3306/alumni","root","root");
        stmt=con.createStatement();
        
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}

 void delete1()
{
    int rows=model.getRowCount();
     int rows1=model1.getRowCount();
      int rows2=model2.getRowCount();
    if(rows>0)
        for(int i=0;i<rows;i++)
        {model.removeRow(0);
       
        
        }
     if(rows1>0)
        for(int i=0;i<rows1;i++)
        {model1.removeRow(0);
       
        
        }
      if(rows2>0)
        for(int i=0;i<rows2;i++)
        {model2.removeRow(0);
       
        
        }
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtDiv = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnId = new javax.swing.JButton();
        btnPass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SCHOOL ID");

        jLabel2.setText("PASS OUT YEAR");

        jLabel3.setText("DIVISION");

        jLabel5.setText("NAME");

        btnId.setText("Search School Id");
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        btnPass.setText("Search Pass Out Year");
        btnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassActionPerformed(evt);
            }
        });

        jButton1.setText("Search Division");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search Name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sid", "name", "gname", "div", "dob", "homead", "eca", "cast"
            }
        ));
        jScrollPane1.setViewportView(tab);

        jTabbedPane.addTab("School Details", jScrollPane1);

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sid", "poy", "age", "city", "charity", "occ", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tab1);

        jTabbedPane.addTab("Alumni Details", jScrollPane2);

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "name", "guardian name", "division", "date of birth", "home address ", "extra curricular activity", "cast", "pass out year", "age", "city", "charity", "occupation", "Gender"
            }
        ));
        jScrollPane3.setViewportView(tab2);

        jTabbedPane.addTab("join", jScrollPane3);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnPass)
                            .addComponent(btnId)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton3)
                        .addGap(107, 107, 107)
                        .addComponent(jButton4)
                        .addGap(59, 59, 59)
                        .addComponent(jButton5)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnId))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPass))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     { jTabbedPane.setEnabledAt(0,true);
    jTabbedPane.setEnabledAt(1,false);
    jTabbedPane.setEnabledAt(2,false);
    try{
        delete1();
        OpenConnection();
        String nm = txtName.getText();
        String query="Select* from schoold where  name like'"+nm+"%';";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next())
        {
        String sid =rs.getString("studentid");
        String name=rs.getString("name");
String eca=rs.getString("eca");
String div=rs.getString("division");
String gname=rs.getString("guardianname");
String cast=rs.getString("cast");
String homead=rs.getString("homeadd");
String dob=rs.getString("dob");
model.addRow(new Object[] {sid,name,gname,div,dob,homead,eca,cast});

            
        }
rs.close();
stmt.close();
con.close();


    }
 catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
}   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
{ jTabbedPane.setEnabledAt(0,true);
    jTabbedPane.setEnabledAt(1,false);
    jTabbedPane.setEnabledAt(2,false);
    try{
        delete1();
        OpenConnection();
        String di = txtDiv.getText();
        String query="Select* from schoold where Division like '"+di+"%';";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next())
        {
             String sid =rs.getString("studentid");
        String name=rs.getString("name");
String eca=rs.getString("eca");
String div=rs.getString("division");
String gname=rs.getString("guardianname");
String cast=rs.getString("cast");
String homead=rs.getString("homeadd");
String dob=rs.getString("dob");
model.addRow(new Object[] {sid,name,gname,div,dob,homead,eca,cast});

            


        }
rs.close();
stmt.close();
con.close();


    }
 catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

  void Clear()
{ txtName.setText("");
txtId.setText("");
txtPass.setText("");
txtDiv.setText("");
jTabbedPane.setEnabledAt(0,true);
    jTabbedPane.setEnabledAt(1,true);
    jTabbedPane.setEnabledAt(2,true);
}
    
    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
{
    jTabbedPane.setEnabledAt(0,false);
    jTabbedPane.setEnabledAt(1,true);
    jTabbedPane.setEnabledAt(2,false);
    try{
        delete1();
        OpenConnection();
        String pass = txtPass.getText();
        String query="Select* from alumnid where poy like '"+pass+"%' ;";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next())
        {
   String sid =rs.getString("studentid");
String poy=rs.getString("poy");  
String age =rs.getString("age");            
String city=rs.getString("city");


String charity=rs.getString("charity");
String occ=rs.getString("occupation");
String gen=rs.getString("gender");
model1.addRow(new Object[] {sid,poy,age,city,charity,occ,gen});

        }
rs.close();
stmt.close();
con.close();

    }
 catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPassActionPerformed

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
          { jTabbedPane.setEnabledAt(0,false);
    jTabbedPane.setEnabledAt(1,false);
    jTabbedPane.setEnabledAt(2,true);
    try{
        delete1();
        OpenConnection();
        String id = txtId.getText();
        String query="Select* from alumniD,schoold where alumnid.studentid=schoold.Studentid and schoold.studentid like '" +id + "%' ;";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next())
        {
          String sid =rs.getString("studentid");
        String name=rs.getString("name");
String eca=rs.getString("eca");
String div=rs.getString("division");
String gname=rs.getString("guardianname");
String cast=rs.getString("cast");
String homead=rs.getString("homeadd");
String dob=rs.getString("dob");  
         
String poy=rs.getString("poy");  
String age =rs.getString("age");            
String city=rs.getString("city");


String charity=rs.getString("charity");
String occ=rs.getString("occupation");
String gen=rs.getString("gender");

model2.addRow(new Object[] {sid,name,gname,div,dob,homead,eca,cast,poy,age,city,charity,occ,gen});
        }
rs.close();
stmt.close();
con.close();


    }
 catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
}    // TODO add your handling code here:
    }//GEN-LAST:event_btnIdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      Clear();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu m1=new Menu();
          m1.show();
           hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable tab;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    private javax.swing.JTextField txtDiv;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
